# Generated by Django 2.1.4 on 2019-09-09 19:41

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('province_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('district_id', models.IntegerField()),
                ('detail_address', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11)),
                ('fix_phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('e_mail', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_default', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('goods_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('goods_name', models.CharField(max_length=255)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pic', models.CharField(max_length=255)),
                ('is_check', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cart',
            },
            bases=(cart.models.Base, models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('satisfaction', models.IntegerField(default=5)),
                ('is_anonymity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=100, unique=True)),
                ('tmoney', models.DecimalField(decimal_places=2, max_digits=7)),
                ('address', models.CharField(default='', max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('pay_type', models.IntegerField(default=1)),
                ('code', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'order',
            },
            bases=(cart.models.Base, models.Model),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('count', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
    ]
