# Generated by Django 2.1.4 on 2019-09-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190909_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_comment',
            field=models.IntegerField(default=0),
        ),
    ]
