# Generated by Django 2.1.4 on 2019-09-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suser', '0001_initial'),
        ('cart', '0003_orderdetail_is_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='goods_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='suser.Goods'),
            preserve_default=False,
        ),
    ]
