# Generated by Django 2.1.4 on 2019-09-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_comment_goods_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='goods_id',
            new_name='goods',
        ),
    ]
